name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          start: |
            npm run start
            npm run start:api
            npm run start:proxy
          wait-on: 'http://localhost:4280'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
          browser: chrome